set_property PACKAGE_PIN H17 [get_ports eq_0]
set_property PACKAGE_PIN K15 [get_ports gr_0]
set_property PACKAGE_PIN J13 [get_ports ls_0]

set_property PACKAGE_PIN M17 [get_ports in1]
set_property PACKAGE_PIN M18 [get_ports in2]
set_property IOSTANDARD LVCMOS33 [get_ports eq_0]
set_property IOSTANDARD LVCMOS33 [get_ports gr_0]
set_property IOSTANDARD LVCMOS33 [get_ports in1]
set_property IOSTANDARD LVCMOS33 [get_ports in2]
set_property IOSTANDARD LVCMOS33 [get_ports ls_0]
